const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const menu=$('.hamb'), nav=$('.nav'); menu?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Fechar menu':'Abrir menu')});
$$('.nav a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
function countdown(){const target=new Date('2026-11-14T00:00:00-03:00').getTime();const now=Date.now();const days=Math.max(0,Math.ceil((target-now)/86400000));const el=$('#days');if(el)el.textContent=days}countdown();setInterval(countdown,3600000);
const people={
 isabella:{name:'Isabella Gonçalves',role:'Rainha',img:'assets/isabella.jpg',text:'Representa a beleza, a força e o orgulho da tradição da XXIII Festa.'},
 maite:{name:'Maite Azevedo',role:'Rainha Mirim',img:'assets/maite.jpg',text:'Uma das representantes mirins da nova geração que mantém viva a tradição.'},
 ana:{name:'Ana Mel',role:'Princesa Mirim',img:'assets/ana.jpg',text:'Representante mirim da XXIII edição, levando simpatia e alegria para a festa.'},
 keylla:{name:'Keylla Almeida',role:'Princesa',img:'assets/keylla.jpg',text:'Representa a juventude e o orgulho de fazer parte dessa história.'},
 denise:{name:'Denise Hora',role:'Amazonas',img:'assets/denise.jpg',text:'Representa a ligação entre a cultura sertaneja, os cavalos e a tradição.'}
};
const modal=$('#modal'), content=$('#modalContent'); function openModal(html){content.innerHTML='<h2 id="modalTitle" class="sr-only">Detalhes</h2>'+html;modal.classList.add('open');modal.setAttribute('aria-hidden','false');modal.querySelector('.close')?.focus()} function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')} document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.classList.contains('open'))closeModal()});
$$('[data-person]').forEach(b=>b.addEventListener('click',()=>{const p=people[b.dataset.person];openModal(`<img class="modal-photo" src="${p.img}" alt="${p.name}"><h3>${p.name}</h3><b>${p.role}</b><p>${p.text}</p><button class="btn copper" onclick="closeModal()">FECHAR</button>`)}));
$('.close')?.addEventListener('click',closeModal);modal?.addEventListener('click',e=>{if(e.target===modal)closeModal()});
$$('.amounts button').forEach(b=>b.addEventListener('click',()=>{$$('.amounts button').forEach(x=>x.classList.remove('active'));b.classList.add('active')}));
$$('.pick-row button').forEach(b=>b.addEventListener('click',()=>{$$('.pick-row button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')}));
$('#continueVote')?.addEventListener('click',()=>{const candidate=$('.pick-row button.selected')?.dataset.candidate||'candidata escolhida';const amount=$('.amounts button.active')?.textContent.trim()||'valor a definir';const text=encodeURIComponent(`Olá! Quero apoiar a candidata ${candidate}. Valor escolhido: ${amount}.`);const url=`https://wa.me/5575982825450?text=${text}`;openModal(`<h3>CONTINUAR PELO WHATSAPP</h3><p>Você será encaminhado para o WhatsApp oficial da organização para concluir o atendimento. O pagamento e a confirmação do apoio ainda dependem da orientação da organização.</p><a class="btn copper" href="${url}" target="_blank" rel="noopener noreferrer">ABRIR WHATSAPP ↗</a>`)});
$('#reg')?.addEventListener('click',()=>openModal('<h3>REGULAMENTO</h3><p>Área reservada para inserir o regulamento oficial da XXIII Festa de Vaqueiros e Fazendeiros.</p><p>Substitua este conteúdo pelo documento aprovado pela organização antes da publicação definitiva.</p>'));
$('.video-card button')?.addEventListener('click',()=>openModal('<h3>A FORÇA DA NOSSA TRADIÇÃO</h3><p>Vídeo demonstrativo do protótipo. O player oficial será conectado quando o material audiovisual for disponibilizado pela organização.</p><button class="btn copper" onclick="document.querySelector(\'#modal\').classList.remove(\'open\')">FECHAR</button>'));

$$('.gallery-grid img').forEach(img=>{const show=()=>openModal(`<img class="gallery-modal-photo" src="${img.src}" alt="${img.alt}"><h3>${img.alt}</h3><button class="btn copper" onclick="closeModal()">FECHAR</button>`);img.addEventListener('click',show);img.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();show()}})});
